build:
  maxIssues: 0

config:
  validation: true

style:
  MagicNumber:
    active: true
    ignoreNumbers: ['-1', '0', '1', '2']
    excludes: ['**/test/**', '**/androidTest/**']
  WildcardImport:
    active: true

complexity:
  CyclomaticComplexMethod:
    active: true
    threshold: 15
  LongParameterList:
    active: true
    threshold: 6

comments:
  UndocumentedPublicClass:
    active: false